//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taxi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cars
    {
        public Cars()
        {
            this.Shifts = new HashSet<Shifts>();
        }
    
        public System.Guid Id { get; set; }
        public string Type { get; set; }
        public string NumberPlate { get; set; }
        public string Description { get; set; }
        public string BodyNumber { get; set; }
        public decimal Kilometrage { get; set; }
        public System.DateTime DateOfLastTS { get; set; }
    
        public virtual ICollection<Shifts> Shifts { get; set; }
    }
}
