//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taxi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drivers
    {
        public Drivers()
        {
            this.Order = new HashSet<Order>();
            this.Shifts = new HashSet<Shifts>();
        }
    
        public System.Guid Id { get; set; }
        public string DriverLicenseId { get; set; }
        public System.DateTime DateOfHiring { get; set; }
        public System.Guid IdEmployee { get; set; }
        public bool Busy { get; set; }
        public string Location { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual ICollection<Order> Order { get; set; }
        public virtual ICollection<Shifts> Shifts { get; set; }
    }
}
