//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taxi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public System.Guid Id { get; set; }
        public System.DateTime DateTime { get; set; }
        public string ClientsPhone { get; set; }
        public string AdressFrom { get; set; }
        public string AdressWhere { get; set; }
        public int Kilometrage { get; set; }
        public System.Guid IdDriver { get; set; }
        public System.Guid IdDispetcher { get; set; }
        public System.Guid IdTariff { get; set; }
        public Nullable<int> Cost { get; set; }
        public string Description { get; set; }
        public System.Guid IdStatus { get; set; }
    
        public virtual Dispetchers Dispetchers { get; set; }
        public virtual Drivers Drivers { get; set; }
        public virtual Tariffs Tariffs { get; set; }
        public virtual Statuses Statuses { get; set; }
    }
}
