//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taxi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TaxiDBEntities : DbContext
    {
        public TaxiDBEntities()
            : base("name=TaxiDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Cars> Cars { get; set; }
        public DbSet<Dispetchers> Dispetchers { get; set; }
        public DbSet<Drivers> Drivers { get; set; }
        public DbSet<Employees> Employees { get; set; }
        public DbSet<Order> Order { get; set; }
        public DbSet<RoleTable> RoleTable { get; set; }
        public DbSet<Shifts> Shifts { get; set; }
        public DbSet<Tariffs> Tariffs { get; set; }
        public DbSet<Statuses> Statuses { get; set; }
        public DbSet<Administators> Administators { get; set; }
    }
}
